---
title: "Possible analyses"
author: "peekbank team"
date: "5/11/2021"
output: html_document
---

```{r setup}
library(here)
library(tidyverse)
library(peekbankr)
library(lme4)

# Seed for random number generation
set.seed(42)
knitr::opts_chunk$set(cache.extra = knitr::rand_seed)
```
# Swingley & Aslin Accuracy Analysis

```{r get_am}
aoi_timepoints <- peekbankr::get_aoi_timepoints(dataset_name = "swingley_aslin_2002", 
                                                
                                         rle=FALSE)
administrations <- peekbankr::get_administrations(dataset_name = "swingley_aslin_2002")

stimuli <- peekbankr::get_stimuli(dataset_name = "swingley_aslin_2002")
trial_types <- peekbankr::get_trial_types(dataset_name = "swingley_aslin_2002")
trials <- peekbankr::get_trials(dataset_name = "swingley_aslin_2002")
```

Let's take Swingley & Aslin (2002) as our test case and see how the condition effect responds to different analytic decisions. 


```{r}
accs <- aoi_timepoints %>%
  left_join(administrations) %>%
  left_join(trials) %>%
  left_join(trial_types) %>%
  filter(condition != "filler") %>%
  mutate(condition = ifelse(condition == "cp", "Correct","Mispronunciation")) %>%
  # mutate(age_group = ifelse(age < mean(age), "13-17", "17-20")) %>%
  group_by(t_norm, administration_id, condition) %>% 
  summarise(correct = mean(aoi == "target") / 
              mean(aoi %in% c("target","distractor"))) %>%
  group_by(t_norm, condition) %>% 
  summarise(ci = 1.96 * sd(correct) / sqrt(length(correct)), 
            correct = mean(correct))

ggplot(accs, aes(x = t_norm, y = correct, col = condition)) + 
  geom_pointrange(aes(ymin = correct - ci, 
                      ymax = correct + ci)) +
  geom_hline(yintercept = .5, lty = 2, col = "black") + 
  langcog::theme_mikabr() + 
  langcog::scale_color_solarized(name = "Age Group") + 
  xlim(-500, 3000) + 
  xlab("Time from target word onset (msec)") + 
  ylab("Proportion correct") + 
  theme(legend.position = "bottom") 
```

```{r}
trial_timecourses <- aoi_timepoints %>%
  left_join(administrations) %>%
  left_join(trials) %>%
  left_join(trial_types) %>%
  filter(condition != "filler") %>%
  mutate(condition = ifelse(condition == "cp", "Correct","Mispronunciation")) 

windows <- expand_grid(start = seq(0, 1500, 100), 
                  end = seq(1500, 3000, 100)) %>%
  filter(end > start) %>%
  mutate(idx = 1:n()) %>%
  split(.$idx) %>%
  map_df(function(df) {
    ms <- trial_timecourses %>%
      filter(t_norm > df$start, t_norm < df$end) %>%
      group_by(administration_id, trial_id, condition) %>% 
      summarise(correct = mean(aoi == "target") / 
                  mean(aoi %in% c("target","distractor"))) 
  
    df$t <- summary(lmer(correct ~ condition + (1 | administration_id), data = ms))$coefficients[2,3]
    return(df)
  })
```

```{r}
ggplot(windows, 
       aes(x = start, y = -t, col = end, group = end)) + 
  geom_line() + 
  ylab("t value") + 
  xlab("Start of analytic window") + 
  viridis::scale_color_viridis(name = "End of analytic window")  + 
  ggtitle("t values for condition effect in an LMM on Swingley & Aslin 2002")
```  
# Potter-Canine

```{r}
aoi_timepoints <- peekbankr::get_aoi_timepoints(dataset_name = "potter_canine", 
                                                
                                         rle=FALSE)
administrations <- peekbankr::get_administrations(dataset_name = "potter_canine")

stimuli <- peekbankr::get_stimuli(dataset_name = "potter_canine")
trial_types <- peekbankr::get_trial_types(dataset_name = "potter_canine")
trials <- peekbankr::get_trials(dataset_name = "potter_canine")
```

```{r}
accs <- aoi_timepoints %>%
  left_join(administrations) %>%
  left_join(trials) %>%
  left_join(trial_types) %>%
  # mutate(age_group = ifelse(age < mean(age), "13-17", "17-20")) %>%
  group_by(t_norm, administration_id, condition) %>% 
  summarise(correct = mean(aoi == "target") / 
              mean(aoi %in% c("target","distractor"))) %>%
  group_by(t_norm, condition) %>% 
  summarise(ci = 1.96 * sd(correct) / sqrt(length(correct)), 
            correct = mean(correct))

ggplot(accs, aes(x = t_norm, y = correct, col = condition)) + 
  geom_pointrange(aes(ymin = correct - ci, 
                      ymax = correct + ci)) +
  geom_hline(yintercept = .5, lty = 2, col = "black") + 
  langcog::theme_mikabr() + 
  langcog::scale_color_solarized(name = "Age Group") + 
  xlim(-500, 4000) + 
  xlab("Time from target word onset (msec)") + 
  ylab("Proportion correct") + 
  theme(legend.position = "bottom") 
```

```{r}
trial_timecourses <- aoi_timepoints %>%
  left_join(administrations) %>%
  left_join(trials) %>%
  left_join(trial_types) 

windows <- expand_grid(start = seq(0, 1500, 100), 
                  end = seq(1500, 3500, 100)) %>%
  filter(end > start) %>%
  mutate(idx = 1:n()) %>%
  split(.$idx) %>%
  map_df(function(df) {
    ms <- trial_timecourses %>%
      filter(t_norm > df$start, t_norm < df$end) %>%
      group_by(administration_id, trial_id, condition) %>% 
      summarise(correct = mean(aoi == "target") / 
                  mean(aoi %in% c("target","distractor"))) 
  
    df$t <- summary(lmer(correct ~ condition + (1 | administration_id), data = ms))$coefficients[4,3]
    return(df)
  })
```

```{r}
ggplot(windows, 
       aes(x = start, y = -t, col = end, group = end)) + 
  geom_line() + 
  ylab("t value") + 
  xlab("Start of analytic window") + 
  viridis::scale_color_viridis(name = "End of analytic window")  + 
  ggtitle("t values for uncommon-low condition in an LMM on Potter Canine")
```  

```{r}
ggplot(windows, 
       aes(x = start, y = end, fill = -t, group = end)) + 
  geom_tile() +
  ylab("End of analytic window") + 
  xlab("Start of analytic window") + 
  viridis::scale_color_viridis(name = "End of analytic window")  + 
  ggtitle("t values for uncommon-low condition in an LMM on Potter Canine")
```  


# RT analysis

Get RTs.

```{r}
source("../helper/get_rt.R")

rt_data <- aoi_timepoints %>%
  filter(any(t_norm == 0), # must have data at 0
         t_norm >= 0) %>% # only pass data after 0
  group_by(administration_id, trial_id) %>%
  summarise(lengths = rle(aoi)$lengths, 
            values = rle(aoi)$values) 

rts <- rt_data %>%
  group_by(administration_id, trial_id) %>%
  nest() %>%
  mutate(data = lapply(data, get_rt)) %>%
  unnest(cols = c(data)) 

rts <- left_join(rts, administrations) %>%
  left_join(trials) %>%
  left_join(trial_types) %>%
  filter(condition != "filler") %>%
  mutate(condition = ifelse(condition == "cp", 
                            "Correct", "Mispronunciation")) %>%
  select(administration_id, trial_id, shift_type, rt, age, condition, english_stimulus_label)
```

Plot RTs. 

```{r}
ggplot(rts, aes(x = rt, fill = shift_type)) + 
  geom_histogram() +
  facet_grid(~condition)
```


